# Generated by Django 5.0.2 on 2026-03-27 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        ('menu', '0001_initial'),
        ('mesas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('notas', models.CharField(blank=True, max_length=255, null=True)),
                ('subtotal_calculado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedido', to='menu.producto')),
                ('promocion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.promocion')),
            ],
            options={
                'verbose_name': 'Detalle de pedido',
                'verbose_name_plural': 'Detalles de pedido',
            },
        ),
        migrations.CreateModel(
            name='DetalleModificador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_extra_aplicado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos', to='menu.opcionmodificador')),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modificadores', to='pedidos.detallepedido')),
            ],
            options={
                'verbose_name': 'Modificador aplicado',
                'verbose_name_plural': 'Modificadores aplicados',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_hora_entrega', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('recibido', 'Recibido'), ('preparando', 'Preparando'), ('listo', 'Listo'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='recibido', max_length=10)),
                ('motivo_cancelacion', models.TextField(blank=True, null=True)),
                ('empleado_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_entregados', to=settings.AUTH_USER_MODEL)),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='catalogs.modalidadingreso')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='mesas.sesioncliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_hora_ingreso'],
            },
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.pedido'),
        ),
        migrations.CreateModel(
            name='SolicitudPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('individual', 'Individual'), ('grupal', 'Grupal')], max_length=10)),
                ('total_individual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_mesa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('propina_sugerida', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.estadosolicitud')),
                ('mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_pago', to='mesas.mesa')),
                ('metodo_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.metodopago')),
                ('sesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_pago', to='mesas.sesioncliente')),
            ],
            options={
                'verbose_name': 'Solicitud de pago',
                'verbose_name_plural': 'Solicitudes de pago',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
