# Generated by Django 5.0.2 on 2026-05-12 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_solicitudpago_campos_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudpago',
            name='detalle_pago',
            field=models.TextField(blank=True, default='', help_text='Desglose del pago para imprimir en ticket.'),
        ),
        migrations.AlterField(
            model_name='solicitudpago',
            name='monto_recibido',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Efectivo físico recibido del cliente.', max_digits=10, null=True),
        ),
    ]
