# Generated by Django 5.0.2 on 2026-03-27 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='GrupoModificador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grupo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('única', 'Única'), ('múltiple', 'Múltiple')], default='única', max_length=10)),
                ('es_obligatorio', models.BooleanField(default=False)),
                ('max_selecciones', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Grupo de modificador',
                'verbose_name_plural': 'Grupos de modificadores',
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('activa', models.BooleanField(default=True)),
                ('codigo_cupon', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('limite_usos', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
            },
        ),
        migrations.CreateModel(
            name='TipoPromocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de promoción',
                'verbose_name_plural': 'Tipos de promoción',
            },
        ),
        migrations.CreateModel(
            name='OpcionModificador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_opcion', models.CharField(max_length=100)),
                ('precio_extra', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='menu.grupomodificador')),
            ],
            options={
                'verbose_name': 'Opción de modificador',
                'verbose_name_plural': 'Opciones de modificador',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen_url', models.CharField(blank=True, max_length=255, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='menu.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.AddField(
            model_name='grupomodificador',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_modificadores', to='menu.producto'),
        ),
        migrations.CreateModel(
            name='PromocionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.producto')),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.promocion')),
            ],
            options={
                'verbose_name': 'Promoción-Producto',
                'unique_together': {('promocion', 'producto')},
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='promociones',
            field=models.ManyToManyField(blank=True, related_name='productos', through='menu.PromocionProducto', to='menu.promocion'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='tipo_promocion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promociones', to='menu.tipopromocion'),
        ),
    ]
