# Generated by Django 5.0.2 on 2026-04-11 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='area',
            field=models.CharField(choices=[('cocina', 'Cocina'), ('bar', 'Bar'), ('ambos', 'Ambos')], default='ambos', max_length=10),
        ),
    ]
