# Generated by Django 5.0.2 on 2026-04-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_opcionmodificador_activo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocionproducto',
            options={'verbose_name': 'Promoción-Producto (legacy)'},
        ),
        migrations.AlterModelOptions(
            name='tipopromocion',
            options={'verbose_name': 'Tipo de promoción (legacy)', 'verbose_name_plural': 'Tipos de promoción (legacy)'},
        ),
        migrations.AlterField(
            model_name='grupomodificador',
            name='es_plantilla',
            field=models.BooleanField(default=False, help_text='Marcar para que aparezca como plantilla reutilizable.'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='aplicacion',
            field=models.CharField(choices=[('item', 'Por ítem'), ('total', 'Sobre total del carrito'), ('combo', 'Combo (precio fijo por conjunto)')], default='item', max_length=20),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='cantidad_minima',
            field=models.PositiveIntegerField(blank=True, help_text='Unidades requeridas para activar la promoción (Lleva X paga Y)', null=True),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='valor_descuento',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje (0-100), monto fijo, precio combo, o cantidad a pagar en Lleva X paga Y', max_digits=10, null=True),
        ),
    ]
