# Generated by Django 5.0.2 on 2026-05-12 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_promocion_descripcion_corta_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='descripcion_corta',
            field=models.CharField(blank=True, help_text='Texto corto para el carrusel (ej: "15% off en bebidas").', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='orden',
            field=models.PositiveSmallIntegerField(default=0, help_text='Orden en el carrusel (menor = primero).'),
        ),
    ]
