# Generated by Django 5.0.2 on 2026-05-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_alter_promocion_descripcion_corta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='dias_semana',
            field=models.CharField(blank=True, default='', help_text='Días en que aplica (0=lun … 6=dom). Vacío = todos los días.', max_length=20),
        ),
    ]
