# Generated by Django 5.0.2 on 2026-03-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('rol', models.CharField(choices=[('mesero', 'Mesero'), ('cajero', 'Cajero'), ('cocina', 'Cocina'), ('gerente', 'Gerente'), ('admin', 'Administrador')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
