# Generated by Django 5.0.2 on 2026-04-17 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_empleado_groups_empleado_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='activo',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='rol',
            field=models.CharField(choices=[('mesero', 'Mesero'), ('cocina', 'Cocina'), ('gerente', 'Gerente'), ('admin', 'Administrador')], default='mesero', max_length=20),
        ),
    ]
