# Generated by Django 5.0.2 on 2026-05-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='valor',
            field=models.TextField(max_length=1000),
        ),
    ]
