# Generated by Django 5.0.2 on 2026-03-27 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_mesa', models.IntegerField(unique=True)),
                ('capacidad', models.IntegerField()),
                ('ubicacion', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_qr', models.CharField(max_length=255, unique=True)),
                ('pin_actual', models.CharField(blank=True, max_length=60, null=True)),
                ('estado', models.CharField(choices=[('libre', 'Libre'), ('ocupada', 'Ocupada')], default='libre', max_length=10)),
                ('id_mesero_asignado', models.ForeignKey(blank=True, limit_choices_to={'rol': 'mesero'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesas_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['numero_mesa'],
            },
        ),
        migrations.CreateModel(
            name='SesionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=50)),
                ('token_cookie', models.CharField(max_length=255, unique=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('pagada', 'Pagada'), ('cerrada', 'Cerrada')], default='activa', max_length=10)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='mesas.mesa')),
                ('modalidad_ingreso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='catalogs.modalidadingreso')),
            ],
            options={
                'verbose_name': 'Sesión de cliente',
                'verbose_name_plural': 'Sesiones de clientes',
                'unique_together': {('mesa', 'alias')},
            },
        ),
    ]
